coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/domain/UserEntity.java
package cz.clovekvtisni.coordinator.server.domain;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.annotation.*;
import cz.clovekvtisni.coordinator.domain.User;
import cz.clovekvtisni.coordinator.domain.UserEquipment;
import cz.clovekvtisni.coordinator.domain.UserSkill;
import cz.clovekvtisni.coordinator.server.security.AuthorizationTool;
import cz.clovekvtisni.coordinator.util.ValueTool;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.*;

/**
 * Created by IntelliJ IDEA.
 * User: tomas
 * Date: 10/26/12
 * Time: 11:07 PM
 */
@Cache
@Entity(name = "User")
public class UserEntity extends AbstractPersistentEntity<User, UserEntity> {

    @Id
    private Long id;

    @NotEmpty
    private String firstName;

    @NotEmpty
    private String lastName;

    @Index
    @NotEmpty
    @Email
    private String email;

    private String password;

    private String phone;

    @Index
    private String organizationId;

    private Date birthday;

    private String addressLine;

    private String city;

    private String zip;

    private String country;

    private Date dateSuspended;

    private String reasonSuspended;

    private String[] roleIdList;

    private Set<String> pushTokensAndroid;

    @Ignore
    private UserEquipmentEntity[] equipmentEntityList;

    @Ignore
    private UserSkillEntity[] skillEntityList;

    public UserEntity() {
    }

    public UserEntity(Long id) {
        setId(id);
    }

    @Override
    protected User createTargetEntity() {
        return new User();
    }

    @Override
    @JsonIgnore
    public Key<UserEntity> getKey() {
        return Key.create(UserEntity.class, id);
    }

    @Override
    public User buildTargetEntity() {
        User user = super.buildTargetEntity();
        if (equipmentEntityList != null) {
            List<UserEquipment> equipmentList = new ArrayList<UserEquipment>(equipmentEntityList.length);
            for (UserEquipmentEntity equipmentEntity : equipmentEntityList) {
                equipmentList.add(equipmentEntity.buildTargetEntity());
            }
            user.setEquipmentList(equipmentList.toArray(new UserEquipment[0]));
        }

        if (skillEntityList != null) {
            List<UserSkill> skillList = new ArrayList<UserSkill>(skillEntityList.length);
            for (UserSkillEntity skillEntity : skillEntityList) {
                skillList.add(skillEntity.buildTargetEntity());
            }
            user.setSkillList(skillList.toArray(new UserSkill[0]));
        }

        return user;
    }

    @Override
    public UserEntity populateFrom(UserEntity entity) {
        return super.populateFrom(entity);
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getAddressLine() {
        return addressLine;
    }

    public void setAddressLine(String addressLine) {
        this.addressLine = addressLine;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Date getDateSuspended() {
        return dateSuspended;
    }

    public void setDateSuspended(Date dateSuspended) {
        this.dateSuspended = dateSuspended;
    }

    public String getReasonSuspended() {
        return reasonSuspended;
    }

    public void setReasonSuspended(String reasonSuspended) {
        this.reasonSuspended = reasonSuspended;
    }

    public String[] getRoleIdList() {
        return roleIdList;
    }

    public void setRoleIdList(String[] roleIdList) {
        this.roleIdList = roleIdList;
    }

    public UserEquipmentEntity[] getEquipmentEntityList() {
        return equipmentEntityList;
    }

    public void setEquipmentEntityList(UserEquipmentEntity[] equipmentEntityList) {
        this.equipmentEntityList = equipmentEntityList;
    }

    public UserSkillEntity[] getSkillEntityList() {
        return skillEntityList;
    }

    public void setSkillEntityList(UserSkillEntity[] skillEntityList) {
        this.skillEntityList = skillEntityList;
    }
    
    public Map<String, UserEquipmentEntity> getEquipmentEntityMap() {
        if (equipmentEntityList == null) return new HashMap<String, UserEquipmentEntity>(); 
        Map<String, UserEquipmentEntity> map = new HashMap<String, UserEquipmentEntity>(equipmentEntityList.length);
        for (UserEquipmentEntity equipmentEntity : equipmentEntityList) {
            map.put(equipmentEntity.getEquipmentId(), equipmentEntity);
        }
        return map;
    }

    public Map<String, UserSkillEntity> getSkillEntityMap() {
        if (skillEntityList == null) return new HashMap<String, UserSkillEntity>();
        Map<String, UserSkillEntity> map = new HashMap<String, UserSkillEntity>(skillEntityList.length);
        for (UserSkillEntity skillEntity : skillEntityList) {
            map.put(skillEntity.getSkillId(), skillEntity);
        }
        return map;
    }

    public String getFullName() {
        if (ValueTool.isEmpty(firstName) && ValueTool.isEmpty(lastName))
            return "";

        else if (ValueTool.isEmpty(firstName))
            return lastName;

        else if (ValueTool.isEmpty(lastName))
            return firstName;

        else
            return lastName + ", " + firstName;
    }

    public String getFullAddress() {
        StringBuilder str = new StringBuilder();
        if (!ValueTool.isEmpty(addressLine))
            str.append(addressLine);
        if (!ValueTool.isEmpty(city))
            str.append((str.length() == 0 ? "" : ", ") + city);
        if (!ValueTool.isEmpty(zip))
            str.append((str.length() == 0 ? "" : ", ") + zip);
        if (!ValueTool.isEmpty(country))
            str.append((str.length() == 0 ? "" : ", ") + country);

        return str.toString();
    }

    public boolean isSuspended() {
        return dateSuspended != null;
    }

    public Set<String> getPushTokensAndroid() {
        if (pushTokensAndroid == null)  pushTokensAndroid = new HashSet<String>();
        return pushTokensAndroid;
    }

    public void setPushTokensAndroid(Set<String> pushTokensAndroid) {
        this.pushTokensAndroid = pushTokensAndroid;
    }

    public boolean isSuperadmin() {
        return roleIdList != null && Arrays.asList(roleIdList).contains(AuthorizationTool.SUPERADMIN);
    }

    @Override
    public String toString() {
        return "UserEntity{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", organizationId='" + organizationId + '\'' +
                ", city='" + city + '\'' +
                ", zip='" + zip + '\'' +
                ", country='" + country + '\'' +
                ", dateSuspended=" + dateSuspended +
                ", reasonSuspended='" + reasonSuspended + '\'' +
                ", roleIdList=" + roleIdList +
                ", addressLine='" + addressLine + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", phone='" + phone + '\'' +
                ", birthday=" + birthday +
                '}';
    }
}

coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/web/model/EventUserForm.java
package cz.clovekvtisni.coordinator.server.web.model;

import com.googlecode.objectify.Key;
import cz.clovekvtisni.coordinator.server.domain.UserEntity;
import cz.clovekvtisni.coordinator.server.domain.UserInEventEntity;

import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: jka
 * Date: 28.11.12
 */
public class EventUserForm extends UserForm {

    @NotNull
    private Long eventId;

    private Long userId;

    private List<Long> groupIdList;

    private Double lastLocationLatitude;

    private Double lastLocationLongitude;

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public UserInEventEntity buildUserInEventEntity() {
        UserInEventEntity inEventEntity = new UserInEventEntity();
        inEventEntity.setLastLocationLatitude(getLastLocationLatitude());
        inEventEntity.setLastLocationLongitude(getLastLocationLongitude());
        inEventEntity.setEventId(eventId);
        Long userId = getUserId();
        if (userId != null) {
            inEventEntity.setUserId(userId);
            inEventEntity.setParentKey(Key.create(UserEntity.class, userId));
        }
        if (groupIdList != null)
            inEventEntity.setGroupIdList(groupIdList.toArray(new Long[0]));

        return inEventEntity;
    }

    public List<Long> getGroupIdList() {
        return groupIdList;
    }

    public void setGroupIdList(List<Long> groupIdList) {
        this.groupIdList = groupIdList;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Double getLastLocationLatitude() {
        return lastLocationLatitude;
    }

    public void setLastLocationLatitude(Double lastLocationLatitude) {
        this.lastLocationLatitude = lastLocationLatitude;
    }

    public Double getLastLocationLongitude() {
        return lastLocationLongitude;
    }

    public void setLastLocationLongitude(Double lastLocationLongitude) {
        this.lastLocationLongitude = lastLocationLongitude;
    }
}

coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/web/controller/AjaxController.java
package cz.clovekvtisni.coordinator.server.web.controller;

import org.springframework.web.bind.annotation.RequestMapping;

/**
 * Created with IntelliJ IDEA.
 * User: tomucha
 * Date: 25.01.13
 * Time: 14:50
 * To change this template use File | Settings | File Templates.
 */
public class AjaxController {

    @RequestMapping
    public String show() {
        return "ajax/demo";
    }
}

coordinator-server/src/main/webapp/WEB-INF/jsp/ajax/assigned-users.jsp
<%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@
        taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@
        taglib prefix="can" uri="/WEB-INF/permissions.tld" %>
<%@
        taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
        %>
<c:forEach items="${assignedUsers}" var="userInEvent" begin="0" step="1" varStatus="i">
<span class="clickable" onclick="onAssignedUserClick(${userInEvent.userId})">${userInEvent.userEntity.fullName} <i class="icon-remove"></i></span>
</c:forEach>

coordinator-server/src/main/webapp/WEB-INF/jsp/ajax/demo.jsp
<%@ page contentType="text/html; charset=UTF-8" language="java" %><%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%@
        taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %><%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %><%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %><%@
        taglib prefix="can" uri="/WEB-INF/permissions.tld" %><%@
        taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %><%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
        %>
<span class="label label-info">Info</span> <span class="label label-info">Info</span> <span class="label label-info">Info</span>

coordinator-server/src/main/webapp/WEB-INF/jsp/ajax/event-users.jsp
<%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@
        taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@
        taglib prefix="can" uri="/WEB-INF/permissions.tld" %>
<%@
        taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
        %>

    <c:choose>
        <c:when test="${!empty userInEvents}">
                <div class="eventListTable">
                    <tags:hiddenEvent/>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <tags:eventUserList renderHeader="true"/>
                        </tr>
                        </thead>
                        <tbody>
                        <c:forEach items="${userInEvents}" var="userInEvent" begin="0" step="1" varStatus="i">
                            <!-- This javascript function should be defined on page which includes picker -->
                            <tr onclick="onUserClick(${userInEvent.userId})" class="clickable">
                                <tags:eventUserList renderHeader="false" user="${userInEvent}"/>
                            </tr>
                        </c:forEach>
                        </tbody>
                    </table>
                </div>
        </c:when>
        <c:otherwise>
            <p><s:message code="msg.noUsersFound"/></p>
        </c:otherwise>

    </c:choose>

coordinator-server/src/main/webapp/WEB-INF/jsp/ajax/poi-popup-new.jsp
<%--@elvariable id="poi" type="cz.clovekvtisni.coordinator.server.domain.PoiEntity"--%>
<%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@
        taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@
        taglib prefix="can" uri="/WEB-INF/permissions.tld" %>
<%@
        taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
        %>

<script type="text/javascript">
    function poiPopupNewSubmit(form) {
        var data = form.serializeArray();
        var container = form.parent();
        container.load(form.attr("action"), data);

        return false;
    }
</script>

<sf:form action="${root}/admin/event/map/ajax/poi-update" modelAttribute="poiForm" onsubmit="return poiPopupNewSubmit($(this))" method="post">
    <sf:errors />

    <div>
    <sf:hidden path="id"/>
    <tags:hiddenEvent/>
    <sf:hidden path="organizationId"/>
    <sf:hidden path="workflowStateId"/>
    <sf:hidden path="confirmed"/>
    <sf:hidden path="longitude" id="mapLongitudeSet"/>
    <sf:hidden path="latitude" id="mapLatitudeSet"/>

    <tags:input field="poiCategoryId" modelAttribute="form" captionCode="PoiEntity.poiCategory" fluid="true">
        <sf:select path="poiCategoryId" items="${config.poiCategoryMap}" itemLabel="name" cssClass="input-medium"/>
    </tags:input>

    <div>
        <tags:input field="name" modelAttribute="form" captionCode="PoiEntity.name" fluid="true">
            <sf:input id="name" path="name"  cssClass="input-medium"/>
        </tags:input>
    </div>

    <div>
        <tags:input field="description" modelAttribute="form" captionCode="PoiEntity.description" fluid="true">
            <sf:textarea id="description" path="description" rows="2"  cssClass="input-medium"/>
        </tags:input>
    </div>

    <div class="btn-group">
    <button class="btn btn-mini btn-primary" type="submit"><s:message code="button.addNew"/></button>
</div>
</sf:form>

coordinator-server/src/main/webapp/WEB-INF/jsp/ajax/poi-popup.jsp
<%--@elvariable id="poi" type="cz.clovekvtisni.coordinator.server.domain.PoiEntity"--%>
<%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@
        taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@
        taglib prefix="can" uri="/WEB-INF/permissions.tld" %>
<%@
        taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
        %>
<h4><img src="${root}${poi.poiCategory.icon}" style="width:1.2em;"/> ${poi.name} <tags:poiStatusIcon poi="${poi}"/></h4>
<p><small>${poi.description}<br/>${poi.poiCategory.name}</small></p>

<c:if test="${not empty poi.workflow}">
    <p><a href="${root}/admin/event/poi/workflow?poiId=<c:out value='${poi.id}'/>&eventId=${poi.eventId}">
        <c:out value="${poi.workflowState.name}"/><br/>
        <small><c:out value="${poi.workflowState.description}"/></small>
    </a></p>
</c:if>

<c:if test="${not empty assignedUsers}">
    <h4><s:message code="label.assignedUsers"/></h4>
    <p>
        <c:forEach items="${assignedUsers}" var="userInEvent" begin="0" step="1" varStatus="i">
            <span>${userInEvent.userEntity.fullName}</span>
        </c:forEach>
    </p>
</c:if>

<div class="btn-group">
    <a class="btn btn-small" onclick="$(this).parents('#mapPopupContainer').load('<s:url value='${root}/admin/event/map/popup/poi?edit=true&eventId=${poi.eventId}&poiId=${poi.id}'/>');return false"><i class="icon-pencil"></i> <s:message code="button.edit"/></a>
</div>

coordinator-server/src/main/webapp/WEB-INF/jsp/ajax/user-popup.jsp
<%--@elvariable id="userInEvent" type="cz.clovekvtisni.coordinator.server.domain.UserInEventEntity"--%>
<%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %>
<%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %>
<%@
        taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@
        taglib prefix="can" uri="/WEB-INF/permissions.tld" %>
<%@
        taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
        %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<h4><img src="${root}/images/icons/male-2.png" style="width: 1.2em;"/><c:out
        value="${userInEvent.userEntity.fullName}"/></h4>

<c:if test="${!empty userInEvent.lastPoiEntity}">
    <p>
        <a href="<s:url value="${root}/admin/event/poi/edit?eventId=${userInEvent.lastPoiEntity.eventId}&poiId=${userInEvent.lastPoiEntity.id}"/>"><c:out
                value="${userInEvent.lastPoiEntity.name}"/></a>
        <tags:poiStatusIcon poi="${userInEvent.lastPoiEntity}"/>
        <br/>
        <small>
            <fmt:formatDate type="both" value="${userInEvent.lastPoiDate}" dateStyle="short" timeStyle="short"/>
        </small>
    </p>
</c:if>


<c:if test="${!empty userInEvent.roles}">
    <p>
        <c:forEach items="${userInEvent.roles}" var="role">
            <span class="label"><c:out value="${config.roleMap[role].name}"/></span>
        </c:forEach>
    </p>
</c:if>
<c:if test="${!empty userInEvent.groupEntities}">
    <p>
    <c:forEach items="${userInEvent.groupEntities}" var="group">
        <span class="label"><c:out value="${group.name}"/></span>
    </c:forEach>
    </p>
</c:if>


<div class="btn-group">
    <a class="btn"
       href="<s:url value="${root}/admin/event/user/edit?userId=${userInEvent.userId}&eventId=${event.id}"/>"><s:message
            code="button.edit"/></a>
</div>