coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/domain/EventEntity.java
package cz.clovekvtisni.coordinator.server.domain;

import com.googlecode.objectify.Key;
import com.googlecode.objectify.annotation.*;
import cz.clovekvtisni.coordinator.domain.Event;
import cz.clovekvtisni.coordinator.domain.EventLocation;
import cz.clovekvtisni.coordinator.server.util.EntityTool;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.Arrays;

/**
 * Created with IntelliJ IDEA.
 * User: jka
 * Date: 5.11.12
 */
@Cache
@Entity(name = "Event")
public class EventEntity extends AbstractPersistentEntity<Event, EventEntity> {

    @Id
    private Long id;

    @Index
    @NotEmpty
    private String eventKey;

    @NotEmpty
    private String name;

    private String description;

    @Ignore
    private EventLocationEntity[] eventLocationEntityList;

    public EventEntity() {
    }

    @Override
    @JsonIgnore
    public Key<EventEntity> getKey() {
        return Key.create(EventEntity.class, id);
    }

    @Override
    protected Event createTargetEntity() {
        return new Event();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEventKey() {
        return eventKey;
    }

    public void setEventKey(String id) {
        this.eventKey = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public EventLocationEntity[] getEventLocationEntityList() {
        return eventLocationEntityList;
    }

    public void setEventLocationEntityList(EventLocationEntity[] eventLocationEntityList) {
        this.eventLocationEntityList = eventLocationEntityList;
    }

    public EventLocationEntity getFirstEventLocation() {
        if (eventLocationEntityList == null || eventLocationEntityList.length == 0) return null;
        return eventLocationEntityList[0];
    }

    @Override
    public Event buildTargetEntity() {
        Event event = super.buildTargetEntity();

        if (eventLocationEntityList != null) {
            event.setLocationList(
                    new EntityTool().buildTargetEntities(Arrays.asList(eventLocationEntityList))
                            .toArray(new EventLocation[0])
            );
        }

        return event;
    }

    @Override
    public String toString() {
        return "EventEntity{" +
                "id=" + id +
                ", eventKey='" + eventKey + '\'' +
                ", name='" + name + '\'' +
                '}';
    }
}

coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/domain/PoiEntity.java
package cz.clovekvtisni.coordinator.server.domain;

import com.beoui.geocell.GeocellManager;
import com.beoui.geocell.model.Point;
import com.googlecode.objectify.Key;
import com.googlecode.objectify.annotation.*;
import cz.clovekvtisni.coordinator.domain.Poi;
import cz.clovekvtisni.coordinator.domain.config.PoiCategory;
import cz.clovekvtisni.coordinator.domain.config.Workflow;
import cz.clovekvtisni.coordinator.domain.config.WorkflowState;
import org.codehaus.jackson.annotate.JsonIgnore;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.NotNull;
import java.util.*;

/**
 * Created with IntelliJ IDEA.
 * User: jka
 * Date: 5.11.12
 */
@Cache
@Entity(name = "Poi")
public class PoiEntity extends AbstractPersistentEntity<Poi, PoiEntity> {

    @Id
    private Long id;

    @Index
    @NotNull
    private Long eventId;

    @Index
    @NotNull
    @NotBlank
    private String name;

    @NotBlank
    private String description;

    @Index
    @NotNull
    private String organizationId;

    @NotNull
    private String poiCategoryId;

    @Index
    private String workflowId;

    @Index
    private String workflowStateId;

    @Index
    private Set<Long> userIdList;

    @NotNull
    private Double latitude;

    @NotNull
    private Double longitude;

    @Index
    private List<String> geoCells;

    private Long precission;

    private boolean confirmed;

    @Ignore
    private PoiCategory poiCategory;

    @Ignore
    private Workflow workflow;

    @Ignore
    private WorkflowState workflowState;

    public PoiEntity() {
    }

    @OnSave
    public void countGeoCells() {
        if (latitude != null && longitude != null) {

            // Transform it to a point
            Point p = new Point(latitude, longitude);

            // Generates the list of GeoCells
            List<String> cells = GeocellManager.generateGeoCell(p);
            geoCells = cells;

        } else {
            geoCells = Collections.EMPTY_LIST;
        }
    }
    @Override
    protected Poi createTargetEntity() {
        return new Poi();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public String getPoiCategoryId() {
        return poiCategoryId;
    }

    public void setPoiCategoryId(String poiCategoryId) {
        this.poiCategoryId = poiCategoryId;
    }

    public String getWorkflowId() {
        return workflowId;
    }

    public void setWorkflowId(String workflowId) {
        this.workflowId = workflowId;
    }

    public String getWorkflowStateId() {
        return workflowStateId;
    }

    public void setWorkflowStateId(String workflowStateId) {
        this.workflowStateId = workflowStateId;
    }

    public Set<Long> getUserIdList() {
        if (userIdList == null) userIdList = new HashSet<Long>();
        return userIdList;
    }

    public void setUserIdList(Set<Long> userIdList) {
        this.userIdList = userIdList;
    }

    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Long getPrecission() {
        return precission;
    }

    public void setPrecission(Long precission) {
        this.precission = precission;
    }

    public boolean isConfirmed() {
        return confirmed;
    }

    public void setConfirmed(boolean confirmed) {
        this.confirmed = confirmed;
    }

    @Override
    @JsonIgnore
    public Key<PoiEntity> getKey() {
        return Key.create(PoiEntity.class, id);
    }

    public PoiCategory getPoiCategory() {
        return poiCategory;
    }

    public void setPoiCategory(PoiCategory poiCategory) {
        this.poiCategory = poiCategory;
    }

    public Workflow getWorkflow() {
        return workflow;
    }

    public void setWorkflow(Workflow workflow) {
        this.workflow = workflow;
        if (workflow != null) {
            this.workflowId = workflow.getId();
        } else {
            this.workflowId = null;
        }
    }

    public WorkflowState getWorkflowState() {
        return workflowState;
    }

    public void setWorkflowState(WorkflowState workflowState) {
        this.workflowState = workflowState;
        if (workflowState != null) {
            this.workflowStateId = workflowState.getId();
        }
    }

    public int getUserCount() {
        return userIdList != null ? userIdList.size() : 0;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "PoiEntity{" +
                "id=" + id +
                ", poiCategoryId=" + poiCategoryId +
                ", workflowId=" + workflowId +
                ", workflowStateId=" + workflowStateId +
                ", userId=" + (userIdList == null ? null : Arrays.asList(userIdList)) +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", precission=" + precission +
                ", confirmed=" + confirmed +
                '}';
    }
}

coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/web/model/ImportFileForm.java
package cz.clovekvtisni.coordinator.server.web.model;

import org.springframework.web.multipart.MultipartFile;

import javax.validation.constraints.NotNull;
import java.io.InputStream;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: jka
 * Date: 21.12.12
 */
public class ImportFileForm {

    @NotNull
    private Long eventId;

    @NotNull
    private String organizationId;

    private InputStream cvsFile;

    public Long getEventId() {
        return eventId;
    }

    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    public String getOrganizationId() {
        return organizationId;
    }

    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    public InputStream getCvsFile() {
        return cvsFile;
    }

    public void setCvsFile(InputStream cvsFile) {
        this.cvsFile = cvsFile;
    }
}

coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/web/controller/EventDetailController.java
package cz.clovekvtisni.coordinator.server.web.controller;

import cz.clovekvtisni.coordinator.exception.MaException;
import cz.clovekvtisni.coordinator.server.domain.EventEntity;
import cz.clovekvtisni.coordinator.server.domain.OrganizationInEventEntity;
import cz.clovekvtisni.coordinator.server.domain.UserEntity;
import cz.clovekvtisni.coordinator.server.filter.EventFilter;
import cz.clovekvtisni.coordinator.server.filter.OrganizationInEventFilter;
import cz.clovekvtisni.coordinator.server.security.AuthorizationTool;
import cz.clovekvtisni.coordinator.server.service.EventService;
import cz.clovekvtisni.coordinator.server.service.OrganizationInEventService;
import cz.clovekvtisni.coordinator.server.tool.objectify.ResultList;
import cz.clovekvtisni.coordinator.server.web.model.EventFilterParams;
import cz.clovekvtisni.coordinator.server.web.model.OrganizationInEventForm;
import cz.clovekvtisni.coordinator.server.web.util.Breadcrumb;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;

/**
 * Created with IntelliJ IDEA.
 * User: jka
 * Date: 20.11.12
 */
@Controller
@RequestMapping("/admin/event/detail")
public class EventDetailController extends AbstractEventController {

    @Autowired
    private EventService eventService;

    @Autowired
    private OrganizationInEventService organizationInEventService;

    @RequestMapping(method = RequestMethod.GET)
    public String getForm(@ModelAttribute("params") EventFilterParams params, Model model) {

        UserEntity user = getLoggedUser();

        if (params.getEventId() != null) {
            OrganizationInEventEntity registration = organizationInEventService.findEventInOrganization(params.getEventId(), user.getOrganizationId(), OrganizationInEventService.FLAG_FETCH_EVENT);
            if (registration == null) {
                // organization doesn't have a OrganizationInEventEntity yet
                registration = new OrganizationInEventEntity();
                registration.setEventEntity(appContext.getActiveEvent());
                registration.setEventId(params.getEventId());
                registration.setOrganizationId(user.getOrganizationId());
            }
            model.addAttribute("form", new OrganizationInEventForm().populateFrom(registration));

            // FIXME: refaktorng

            //populateEventModel(model, new EventFilterParams(registration.getEventEntity()));
            //model.addAttribute("event", registration.getEventEntity());

        } else {
            throw new IllegalStateException("Null eventId");
        }

        populateModel(model);

        return "admin/event-detail";
    }

    @RequestMapping(method = RequestMethod.POST)
    public String createOrUpdate(@ModelAttribute("form") @Valid OrganizationInEventForm form, BindingResult bindingResult, Model model) {
        if (bindingResult.hasErrors()) {

            //
            // populateEventModel(model, new EventFilterParams(loadEventById(form.getEventKey())));
            populateModel(model);
            return "admin/event-detail";
        }

        try {
            OrganizationInEventEntity entity = new OrganizationInEventEntity().populateFrom(form);
            if (entity.isNew())
                organizationInEventService.create(entity);
            else
                organizationInEventService.update(entity);

        } catch (MaException e) {
            // FIXME: refaktoring
            //populateEventModel(model, new EventFilterParams(loadEventById(form.getEventKey())));
            addFormError(bindingResult, e);
            populateModel(model);
            return "admin/event-detail";
        }

        return "redirect:/admin/event/map?eventId="+form.getEventId();
    }

    protected void populateModel(Model model) {
        UserEntity loggedUser = getLoggedUser();
        if (loggedUser.getOrganizationId() == null) return;
        OrganizationInEventFilter filter = new OrganizationInEventFilter();
        filter.setOrganizationIdVal(loggedUser.getOrganizationId());
        List<EventEntity> inEvents = eventService.findByOrganizationFilter(filter, 0, null, 0l).getResult();
        ResultList<EventEntity> allEvents = eventService.findByFilter(new EventFilter(), 0, null, 0l);
        List<EventEntity> result = new ArrayList<EventEntity>();
        for (EventEntity event : allEvents.getResult()) {
            if (!inEvents.contains(event))
                result.add(event);
        }

        model.addAttribute("eventList", result);
    }

    public static Breadcrumb getBreadcrumb(EventEntity params) {
        return new Breadcrumb(params, "/admin/event/detail", "breadcrumb.eventDetail", AuthorizationTool.ADMIN);
    }
}

coordinator-server/src/main/java/cz/clovekvtisni/coordinator/server/web/controller/EventPoiWorkflowController.java
package cz.clovekvtisni.coordinator.server.web.controller;

import cz.clovekvtisni.coordinator.server.domain.PoiEntity;
import cz.clovekvtisni.coordinator.server.service.PoiService;
import cz.clovekvtisni.coordinator.server.service.UserGroupService;
import cz.clovekvtisni.coordinator.server.service.UserInEventService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

/**
 * Created with IntelliJ IDEA.
 * User: jka
 * Date: 5.12.12                                                                                                Ò
 */
@Controller
@RequestMapping("/admin/event/poi/workflow")
public class EventPoiWorkflowController extends AbstractEventController {

    @Autowired
    private PoiService poiService;

    @Autowired
    private UserGroupService userGroupService;

    @RequestMapping(method = RequestMethod.GET)
    public String edit(
            @RequestParam(value = "eventId", required = true) Long eventId,
            @RequestParam(value = "poiId", required = true) Long poiId,
            Model model) {

        PoiEntity poi = poiService.findById(poiId, 0);
        model.addAttribute("poi", poi);
        model.addAttribute("userGroups", userGroupService.findByEventId(appContext.getActiveEvent().getId(), 0l));
        return "admin/event-poi-workflow";
    }

    @RequestMapping(method = RequestMethod.GET, value = "/transition")
    public String changeWorkflowState(
            @RequestParam(value = "eventId", required = true) Long eventId,
            @RequestParam(value = "poiId", required = true) Long poiId,
            @RequestParam(value = "transitionId", required = true) String transitionId,
            Model model) {
        PoiEntity poi = poiService.findById(poiId, 0l);

        String goingToState = poi.getWorkflowState().getTransitionMap().get(transitionId).getToStateId();
        if (poi.getWorkflow().getStateMap().get(goingToState).isRequiresAssignment()) {
            // new state requires assigned users
            if (poi.getUserIdList().isEmpty())  {
                setGlobalMessage(getMessage("label.missingAssignee"), model);
                return edit(eventId, poiId, model);
            }
        }

        poiService.transitWorkflowState(poi, transitionId, PoiService.FLAG_DISABLE_FORCE_SINGLE_ASSIGN);
        return "redirect:/admin/event/poi/list?eventId=" + eventId;

    }

}

coordinator-server/src/main/webapp/WEB-INF/jsp/admin/error.jsp
<%@ page contentType="text/html; charset=UTF-8" language="java" %><%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %><%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %><%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%@
        taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %><%@
        taglib prefix="tags" tagdir="/WEB-INF/tags" %>

<%--@elvariable id="exceptionMessage" type="java.lang.String"--%>
<%--@elvariable id="exceptionStack" type="java.lang.String"--%>
<%--@elvariable id="exceptionCode" type="java.lang.String"--%>
<%--@elvariable id="exceptionCause" type="java.lang.String"--%>
<%--@elvariable id="exceptionCauseMessage" type="java.lang.String"--%>

<div class="error">
    <h2>${exceptionMessage}</h2>
    <p><strong><c:out value="${exceptionCode}"/></strong></p>
    <p>${exceptionCause}: ${exceptionCauseMessage}</p>

    <textarea cols="80" rows="20" class="help" style="width: 100%">
        <c:out value="${exceptionStack}"/>
    </textarea>
</div>

coordinator-server/src/main/webapp/WEB-INF/jsp/admin/event-map.jsp
<%@
    taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%@
    taglib prefix="s" uri="http://www.springframework.org/tags" %><%@
    taglib prefix="sf" uri="http://www.springframework.org/tags/form" %><%@
    taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %><%@
    taglib prefix="www" uri="/WEB-INF/www.tld" %><%@
    taglib prefix="tags" tagdir="/WEB-INF/tags"
%>
<script type="text/javascript">

    var eventId = ${event.id};
    function initialize() {
        CoordinatorMap.setOnClickAddPoint(TYPE_POI, "${root}/admin/event/map/popup/poi?eventId=${event.id}");
        refreshMarkers();
    }

    function fillPoiMarkers(bounds) {
        var url = root+"/admin/event/map/api/poi";
        var decodedRequest = $("#filterForm").serialize();

        $.getJSON(url, decodedRequest, function(response, txt) {
            $.each(response, function(i, item) {
                item.popupUrl = "${root}/admin/event/map/popup/poi?poiId="+item.id+"&eventId=${event.id}",
                item.type = TYPE_POI;
                item.icon = ICON_POI[item.poiCategoryId];
                CoordinatorMap.addPoint(item);
            });
        });
    }

    function fillUserMarkers() {
        var url = root+"/admin/event/map/api/user";
        var decodedRequest = $("#filterForm").serialize();

        $.getJSON(url, decodedRequest, function(response, txt) {
            $.each(response, function(i, item) {
                item.name = item.userEntity.fullName;
                item.popupUrl = "${root}/admin/event/map/popup/user?userId="+item.userId+"&eventId=${event.id}",
                item.type = TYPE_USER;
                item.icon = ICON_USER;
                item.latitude = item.lastLocationLatitude;
                item.longitude = item.lastLocationLongitude;
                CoordinatorMap.addPoint(item);
            });
        });
    }

    function boundsToFilterForm(bounds) {
        var url = root+"/admin/event/map/api/user";
        var arrBounds = bounds.toArray(); //array order: left, bottom, right, top
        $("#inputLatS").val(arrBounds[1]);
        $("#inputLatN").val(arrBounds[3]);
        $("#inputLonW").val(arrBounds[0]);
        $("#inputLonE").val(arrBounds[2]);
    }

    function refreshMarkers() {
        CoordinatorMap.clearMarkers();
        var bounds = map.getExtent();
        var proj = new OpenLayers.Projection("EPSG:4326");
        bounds.transform(map.getProjectionObject(), proj);
        boundsToFilterForm(bounds);

        if ($("#showpois").prop("checked")) {
            fillPoiMarkers();
            $("#poisFilter").slideDown();
        } else
            $("#poisFilter").slideUp();

        if ($("#showusers").prop("checked")) {
            fillUserMarkers();
            $("#usersFilter").slideDown();
        } else
            $("#usersFilter").slideUp();
    }
</script>

<div>
    <div>
    <tags:osm
            width="90%"
            height="500px"
            latitude="${event.firstEventLocation.latitude}"
            longitude="${event.firstEventLocation.longitude}"
            onLoad="initialize()"
            onMapChange="refreshMarkers()"
            />
    <sf:form modelAttribute="params" id="filterForm" onsubmit="return false">
        <div class="container-fluid">
            <tags:hiddenEvent/>

            <input type="hidden" id="inputLatS" name="latS"/>
            <input type="hidden" id="inputLatN" name="latN"/>
            <input type="hidden" id="inputLonW" name="lonW"/>
            <input type="hidden" id="inputLonE" name="lonE"/>

            <div class="row-fluid">
                <div class="span5">
                    <label class="checkbox"><input type="checkbox" id="showusers" onchange="refreshMarkers()" checked="checked"/> <s:message code="label.showUsers"/></label>
                    <div id="usersFilter">
                        <label><s:message code="label.group"/>:</label>
                        <sf:select path="groupId" onchange="refreshMarkers()">
                            <sf:option value=""/>
                            <sf:options items="${userGroups}" itemLabel="name" itemValue="id"/>
                        </sf:select>
                        <label><s:message code="label.name"/>:</label> <sf:input path="userFulltext" onchange="refreshMarkers()"/>
                    </div>
                </div>
                <div class="span5">
                    <label class="checkbox"><input type="checkbox" id="showpois" onchange="refreshMarkers()" checked="checked"/> <s:message code="label.showPois"/></label>
                    <div id="poisFilter">
                        <label><s:message code="label.workflow"/>:</label>
                        <sf:select path="workflowId" onchange="refreshMarkers()">
                            <sf:option value=""/>
                            <sf:options items="${config.workflowList}" itemLabel="name" itemValue="id"/>
                        </sf:select>
                        <label><s:message code="label.workflowState"/>:</label>
                        <sf:select path="workflowStateId" onchange="refreshMarkers()">
                            <sf:option value=""/>
                            <c:forEach items="${config.workflowList}" var="workflow">
                                <c:forEach items="${workflow.states}" var="state">
                                    <sf:option value="${state.id}">${workflow.name} &gt; ${state.name}</sf:option>
                                </c:forEach>
                            </c:forEach>
                        </sf:select>
                    </div>
                </div>
            </div>
        </div>
    </sf:form>
    </div>
</div>

coordinator-server/src/main/webapp/WEB-INF/jsp/admin/event-poi-edit.jsp
<%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %><%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %><%@
        taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %><%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
%><script type="text/javascript">

    function onNewPoint(point) {
       $("#latitudeInput").val(point.latitude);
       $("#longitudeInput").val(point.longitude);
    }

    function initialize() {
        CoordinatorMap.setOnClickAddPoint(TYPE_POI);

        <c:if test="${!empty form.latitude and !empty form.longitude}">
            CoordinatorMap.addPoint({
                type: TYPE_POI,
                icon: ICON_GENERIC,
                poiId: <c:out value="${form.id}"/>,
                longitude: <c:out value="${form.longitude}"/>,
                latitude: <c:out value="${form.latitude}"/>
            });
            </c:if>
    }

</script>

<h2>
    <s:message code="${form.new ? 'header.poiCreate' : 'header.poiEdit'}"/>
</h2>

<div class="fluid">
    <div class="row-fluid">
        <div class="mini-layout span4">
            <sf:form method="POST" action="${root}/admin/event/poi/edit" modelAttribute="form">

                <sf:errors />

                <div>
                    <sf:hidden path="id"/>
                    <tags:hiddenEvent/>
                    <sf:hidden path="organizationId"/>
                    <sf:hidden path="workflowStateId"/>
                    <sf:hidden path="confirmed"/>

                    <tags:input field="poiCategoryId" modelAttribute="form" captionCode="PoiEntity.poiCategory">
                        <sf:select path="poiCategoryId" items="${config.poiCategoryMap}" itemLabel="name"/>
                    </tags:input>

                    <div>
                        <tags:input field="name" modelAttribute="form" captionCode="PoiEntity.name">
                            <sf:input id="name" path="name"/>
                        </tags:input>
                    </div>

                    <div>
                        <tags:input field="description" modelAttribute="form" captionCode="PoiEntity.description">
                            <sf:textarea id="description" path="description" rows="3"/>
                        </tags:input>
                    </div>

                    <div>
                        <tags:input field="longitude" modelAttribute="form" captionCode="PoiEntity.longitude">
                            <sf:input id="longitudeInput" path="longitude" readonly="true"/>
                        </tags:input>
                    </div>

                    <div>
                        <tags:input field="latitude" modelAttribute="form" captionCode="PoiEntity.latitude">
                            <sf:input id="latitudeInput" path="latitude" readonly="true"/>
                        </tags:input>
                    </div>



    <%--
                                        <div>
                                            <tags:input field="precission" modelAttribute="form" captionCode="PoiEntity.precission">
                                                <sf:input path="precission"/>
                                            </tags:input>
                                        </div>

                                        <div>
                                            <tags:input field="workflowId" modelAttribute="form" captionCode="PoiEntity.workflow">
                                                <sf:select id="workflowSelect" path="workflowId">
                                                    <sf:option value=""><s:message code="label.emptyWorkflow"/></sf:option>
                                                    <c:forEach items="${config.workflowMap}" var="entry">
                                                        <sf:option value="${entry.key}" label="${entry.value.name}"/>
                                                    </c:forEach>
                                                </sf:select>
                                            </tags:input>
                                        </div>--%>

                    <%--<div>--%>
                        <%--<tags:input field="assignedUsers" modelAttribute="form" captionCode="label.assignedUsers">--%>
                            <%--<sf:checkboxes path="assignedUsers" items="${users}" itemValue="id" itemLabel="fullName"/>--%>
                        <%--</tags:input>--%>
                    <%--</div>--%>
                </div>

                <div class="buttonPanel">
                    <button type="submit" class="btn btn-primary"><span class="icon-ok icon-white"></span> <s:message code="button.save"/></button>
                </div>


            </sf:form>
        </div>
        <div class="mini-layout span4">
            <tags:osm
                    width="400px"
                    height="300px"
                    longitude="${!empty form.longitude ? form.longitude : event.firstEventLocation.longitude}"
                    latitude="${!empty form.latitude ? form.latitude : event.firstEventLocation.latitude}"
                    zoom="13"
                    onLoad="initialize()"
                    onNewPoint="onNewPoint"
                    maxPoints="poi=1"
                    buttons="addPoi"
                    />

        </div>
    </div>
</div>

coordinator-server/src/main/webapp/WEB-INF/jsp/admin/home.jsp
<%@ page contentType="text/html; charset=UTF-8" language="java" %><%@
        taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %><%@
        taglib prefix="s" uri="http://www.springframework.org/tags" %><%@
        taglib prefix="sf" uri="http://www.springframework.org/tags/form" %><%@
        taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %><%@
        taglib prefix="tags" tagdir="/WEB-INF/tags"
%>
<%--@elvariable id="event" type="cz.clovekvtisni.coordinator.server.domain.EventEntity"--%>
<p class="lead"><c:out value="${event.name}"/></p>
home page admin